### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by imkrmgn** [CatalystCode/SpeechToText-WebSockets-Java#3]
Hi @c-w.

I am hoping that the next version 0.0.8 will be released in the maven central repository, but is there a plan for that?

**Comment by c-w** [comment]
Hi @imkrmgn. We don't have any plans for releasing a new version at this point. If you'd like to set up a CD pipeline to publish new jars to Maven Central via Travis, that would be a much appreciated pull request!

In the meantime, you can use Maven local repositories and the maven-install tool as described on [StackOverflow](https://stackoverflow.com/a/28762617/3817588) to add newer versions of the dependency if that's a requirement for you.

```xml
  <repositories>
    <repository>
      <id>local-jars</id>
      <url>file://${basedir}/repo</url>
    </repository>
  </repositories>
...
  <dependencies>
    <dependency>
      <groupId>local</groupId>
      <artifactId>stt</artifactId>
      <version>0.0.8</version>
    </dependency>
</dependencies>
```
